### PR TITLE
Update BoardConfig.mk

### PR DESCRIPTION
**Pull request by kirito96**
Either use kernel source to compile or prebuilt kernel not both

### CODE REVIEW

**Comment by Charles-IV** [comment]
Ahh, I assumed that by default it used kernel source, even if both were defined.
I think I'll use kernel source, that way it stays up to date (of I ever update it lol)
Do I simply comment out target prebuilt kernel

**Comment by Charles-IV** [comment]
I remember trying to find the option on whether to use it or not, to make sure it didn't, but if target prebuilt kernel is it, I guess I cement it out?

**Comment by kirito96** [comment]
Yeah, comment it out. Also on the device**.mk. Remove the lines referring to the kernel (comment it out or remove it)

**Comment by Charles-IV** [comment]
Sorry I'm a bit unorganised right now aren't I!

**Pull request closed without merging**
