### PR TITLE
Update BoardConfig.mk

### PR DESCRIPTION
**Pull request by kirito96**
to build with the kernel source

### CODE REVIEW

**Comment by kirito96** [comment]
This results in build errors, currently working on a fix.

**Comment by Charles-IV** [comment]
As I'm in UK and it's late, i I'll probably pull this in the morning, although I think I may not be able to do much, so maybe even later. Hopefully you would have found a fix by then!
I see what your going at here. I've missed a few configs by the looks of it. I'll probably compare it to my grouper tree (forked of aaopt's). One thing I noticed straight away, I think cross compile prefix needs a version number. I think it references GCC, and from memory, I think n uses something like 4.8(or 9! Not sure), but I saw on the cm for mtk thread u said you've never managed to use one version. Have a look at buildkernel.sh and see what I used

**Comment by kirito96** [comment]
Alright, I'll take a look at the buildkernel.sh. I posted in the TWRP thread and hoping I can get an answer by tomorrow morning.

**Comment by kirito96** [comment]
I see what you were saying about the prefix. This line https://github.com/Charles-IV/lineageos_android_device_asus_grouper/blob/cm-14.1/BoardConfigCommon.mk#L111

**Pull request closed without merging**
